name: Build and Test

on:
  workflow_dispatch: 
  push: 
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@1.87.0
      - run: cargo test --verbose --no-fail-fast
